image: "ubuntu:20.04"

stages:
  - publish

ğŸš€ publish package:
  stage: publish
  only: 
    - tags
  script:
    - apt-get update
    - apt-get install -y curl zip jq git
    - git --version
    - cd .release
    - chmod +x release.sh
    - ./release.sh
